### PR TITLE
feat: add doc example for implementing the interface

### LINKED ISSUE #23: Examples in docs or ReadMe?
Should the documentation or the ReadMe (or both) contain some examples of how to use SciMLStructures? I'm there must be some examples out there, but don't know where they are (and the tests here don't have any examples either).

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Close #23 

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
Requires SciML/SciMLSensitivity.jl#1131

**Comment by ChrisRackauckas** [comment]
@DhairyaLGandhi can you look into this?

**Comment by DhairyaLGandhi** [comment]
Yes, let me take a look

**Comment by albertomercurio** [comment]
Hello, is it possible to add an example that also includes `Constants`, `Caches` and `Discrete`? How do we use the `repack` and `replace` functions for any of them? Is it exactly the same as for `Tunable` parts?

**Comment by AayushSabharwal** [comment]
>  is it possible to add an example that also includes Constants, Caches and Discrete?

I'll add `Constants` here, and mention that caches and discrete are identical. 

> How do we use the repack and replace functions for any of them? Is it exactly the same as for Tunable parts?

Basically yeah.

> Moreover, what if I have different Caches like a Vector and a Matrix? Should I canonicalize them as a vector? 

Yes, they need to be flattened and concatenated

> Also for the Discrete I may have many different types.

They need to be concatenated into one type-unstable array

**Comment by ChrisRackauckas** [comment]
What's left here?

**Comment by AayushSabharwal** [comment]
I have the doc changes ready, SciMLSensitivity needs a tag

**Comment by ChrisRackauckas** [comment]
All of the SciMLStructures changes that were ready were tagged last week?

**Comment by ChrisRackauckas** [comment]
🎉

**Pull request merged**
